name: Code Checks

on: pull_request

defaults:
  run:
    shell: bash

jobs:
  spelling-check:
    name: Spelling Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check spelling
        uses: crate-ci/typos@v1.22.7
        with:
          files: ./_posts ./README.md ./about/faq.md ./about/contributing.md

  javascript-check:
    name: JavaScript Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install JS tools
        run: npm install prettier

  python-check:
    name: Python Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install Python tools
        run: pip install flake8 black
      - run: make test
